# Generated by Django 3.2.9 on 2021-11-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20211106_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='jojo',
            name='date',
            field=models.DateField(default='2021-12-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jojo',
            name='organizer_email',
            field=models.EmailField(default='bruh@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
